# Generated by Django 3.0.5 on 2020-04-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='opentb_session_key',
            new_name='opentdb_session_key',
        ),
    ]
