# Generated by Django 3.0.5 on 2020-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20200428_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='category',
            field=models.IntegerField(choices=[(0, 'Any Category'), (9, 'General Knowledge'), (10, 'Entertainment: Books'), (11, 'Entertainment: Film'), (12, 'Entertainment: Music'), (13, 'Entertainment: Musicals & Theatres'), (14, 'Entertainment: Television'), (15, 'Entertainment: Video Games'), (16, 'Entertainment: Board Games'), (17, 'Science & Nature'), (18, 'Science: Computers'), (19, 'Science: Mathematics'), (20, 'Mythology'), (21, 'Sports'), (22, 'Geography'), (23, 'History'), (24, 'Politics'), (25, 'Art'), (26, 'Celebrities'), (27, 'Animals'), (28, 'Vehicles'), (29, 'Entertainment: Comics'), (30, 'Science: Gadgets'), (31, 'Entertainment: Japanese Anime & Manga'), (32, 'Entertainment: Cartoon & Animations')], default=0),
        ),
        migrations.AlterField(
            model_name='round',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
