# Generated by Django 3.0.5 on 2020-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20200430_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestate',
            name='slug',
            field=models.SlugField(default='bob'),
            preserve_default=False,
        ),
    ]
