# Generated by Django 3.0.5 on 2020-05-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_activestate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='activestate',
            name='answers',
            field=models.BooleanField(default=False),
        ),
    ]
